-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRNuOLqjIGNrjcSrv
1nXloHYnIJpB0ctaqUHinpgKBhygCgYIKoZIzj0DAQehRANCAASyfwD5uWECNhwB
S4jPSV0cwOfTu77rpwelDvAd6Gaal9l+iPvdY+CtNr2eq56qZ0qgIji21X6HIkP7
f/ruPvHy
-----END PRIVATE KEY-----